function [j] = ReadHeader(fp)
%UNTITLED3 Summary of this function goes here
%   Detailed explanation goes here
% read file header
t = fread(fp,1,'uint8');
fseek(fp,0,-1);
fseek(fp,0,-1);
% if the file start with "{", it's generated by ver-0.0.0
if(t == 123)
    hdr_size = 1024;
else
    hdr_size = fread(fp,1,'uint32');
end
hdr_size
d = fread(fp,hdr_size,'uint8');
l = length(find(d));
s = sprintf("%s",d(1:l));
j = jsondecode(s);
end